#compiling all files in macOS usgin clang
all:
	clang -c ./src/appName.c -I ./include -o ./obj/appName.o

#run the program compiled
run:
	echo "run program"
	./bin/appName

#delete all files in bin and obj directory
clean:
	rm	./bin/* ./obj/*    